export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";

export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAIL = "GET_CATEGORY_FAIL";

export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const GET_FOOD_SUCCESS = "GET_FOOD_SUCCESS";
export const GET_FOOD_FAIL = "GET_FOOD_FAIL";

export const GET_PARTNER_FOOD_SUCCESS = "GET_PARTNER_FOOD_SUCCESS";
export const GET_PARTNER_FOOD_FAIL = "GET_PARTNER_FOOD_FAIL";

export const RESET_CARD = "RESET_CARD"

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const ADD_TO_CARD_SUCESS = "ADD_TO_CARD_SUCCESS";
export const ADD_TO_CARD_FAIL = "ADD_TO_CARD_FAIL";
export const REMOVE_FROM_CARD = "REMOVE_FROM_CARD";